export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const ADD_CUSTOMER = "ADD_CUSTOMER";
